# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160609_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionaryresult',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('IN_PROGRESS', 'In progress'), ('DONE', 'Done')], default='CREATED', max_length=20),
        ),
    ]
