# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 10:45
from __future__ import unicode_literals

from django.db import migrations

def set_default_email(apps, schema_editor):
    User = apps.get_model("core", "User")
    for user in User.objects.all():
        if not user.email:
            if user.username == "admin":
                user.email = "admin@multigence.com"
            else:
                user.email = "%s.%s@multigence.com" % (user.first_name , user.last_name)
            user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160609_0819'),
    ]

    operations = [
        migrations.RunPython(set_default_email),
    ]
