# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-10 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160609_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('APPLICANT', 'Applicant'), ('MANAGER', 'Company manager')], default='EMPLOYEE', max_length=20),
        ),
    ]
