# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-04 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20160628_0921'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionaryresult',
            unique_together=set([('user', 'questionary')]),
        ),
    ]
