# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-07 08:34
from __future__ import unicode_literals

from django.db import migrations


def set_positions(apps, schema_editor):
    User = apps.get_model("core", "User")
    Position = apps.get_model("core", "Position")
    for p in Position.objects.all():
        user = User.objects.get(uuid=p.user_uuid)
        user.position = p
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20160707_0829'),
    ]

    operations = [
        migrations.RunPython(set_positions),
        migrations.RemoveField(
            model_name='position',
            name='user_uuid',
        ),

    ]
