# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-07 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20160707_0834'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='department',
            unique_together=set([('name', 'company')]),
        ),
    ]
