# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-12 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20160707_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='trial',
            field=models.BooleanField(default=False),
        ),
    ]
