# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-13 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_company_trial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
