# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-15 07:44
from __future__ import unicode_literals

from django.db import migrations


def lower_case_emails(apps, schema_editor):
    User = apps.get_model("core", "User")
    for user in User.objects.all():
        user.email = user.email.lower()
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20160713_1438'),
    ]

    operations = [
        migrations.RunPython(lower_case_emails),
    ]
