# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-15 15:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20160715_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionaryresult',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='questionaryresult',
            unique_together=set([]),
        ),
    ]
