# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-03 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20160802_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionary',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Company'),
        ),
    ]
