# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-16 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20160803_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='invitations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='invitations_sent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_alias',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_alias',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
