# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-16 18:03
from __future__ import unicode_literals

from django.db import migrations

from multigence_server.core import services


def set_aliases(apps, schema_editor):
    User = apps.get_model("core", "User")
    for user in User.objects.all():
        first_name_alias, last_name_alias = services.get_random_name()
        if not user.first_name_alias:
            user.first_name_alias = first_name_alias
        if not user.last_name_alias:
            user.last_name_alias = last_name_alias
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20160816_1144'),
    ]

    operations = [
        migrations.RunPython(set_aliases),
    ]
