# Generated by Django 4.1.7 on 2023-03-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20160816_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='text',
            field=models.JSONField(),
        ),
    ]
