# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-10 12:50
from __future__ import unicode_literals

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_auto_20160610_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('APPLICANT', 'Applicant'), ('MANAGER', 'Company manager')], default='EMPLOYEE', max_length=20)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('position', models.CharField(blank=True, max_length=512, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Department')),
                ('questionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Questionary')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together=set([('email', 'questionary')]),
        ),
    ]
