# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-13 15:26
from __future__ import unicode_literals

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 13, 15, 26, 47, 131714, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invitation',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
