# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-12 08:29
from __future__ import unicode_literals

from django.db import migrations

from multigence_server.core.services import get_default_department


def set_deparment_of_invitation(apps, schema_editor):
    Invitation = apps.get_model("registration", "Invitation")
    for invitation in Invitation.objects.all():
        if not invitation.department:
            invitation.department = get_default_department(invitation.questionary.company)
            invitation.save()

class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20160801_1600'),
    ]

    operations = [
        migrations.RunPython(set_deparment_of_invitation),
    ]
