# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-12 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20160912_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Department'),
        ),
    ]
