# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-12 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20160912_0829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='questionary',
        ),
    ]
