"""
Django settings for multigence_server project.

Generated by 'django-admin startproject' using Django 1.9.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import ast
import os
import datetime

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'yks6#5-(c@6!)ewm$*1qw%kad43e31bg^iu$&4bv3k+y!y*)f4'

DEBUG = ast.literal_eval(os.environ.get('MG_DEBUG', "False"))

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',

    'multigence_server.api',
    'multigence_server.report',
    'multigence_server.emailing',
    'multigence_server.registration',
    'multigence_server.core',

    'djrill'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'debug': DEBUG,
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

REST_FRAMEWORK = {
    'FORM_METHOD_OVERRIDE': None,
    'FORM_CONTENT_OVERRIDE': None,
    'DEFAULT_MODEL_SERIALIZER_CLASS': 'drf_toolbox.serializers.ModelSerializer',
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    )

}

AUTH_USER_MODEL = 'core.User'

# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = 'https://s3.eu-central-1.amazonaws.com/statics.multigence.com/static/'

#
# Multigence Settings
#

# The language codes for questions, options, templates. First code is default
MULTIGENCE_LANGUAGES = ['en', 'de', 'pt']

TOKEN_TIMEOUT = datetime.timedelta(hours=24).total_seconds()
TOKEN_SECRET="test"

# Mail integration
# Django & Djrill settings to send errors to admins
ADMINS = [('Ferhat', 'ferhat.ipek@xailabs.de'), ('Xailabs', 'it-support@xailabs.de'), ('stefan', 'visentin@xailabs.de')]
EMAIL_BACKEND = os.environ.get("MULTIGENCE_EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")
DEFAULT_FROM_EMAIL = "it-support@xailabs.de"
SERVER_EMAIL = DEFAULT_FROM_EMAIL
MAIL_API_KEY = "7mII2nzrlAEYOKUImujNUg" #os.environ.get('MANDRILL_API_KEY')
MANDRILL_API_KEY = MAIL_API_KEY

INTERCEPT_EMAIL_MODE = ast.literal_eval(os.environ.get('INTERCEPT_EMAIL_MODE', "False"))

# Email addresses
MULTIGENCE_SENDER_NAME = "Culture Pattern Tool"
NO_REPLY_EMAIL = "it-support@xailabs.de"
ADMIN_EMAIL = "ferhat.ipek@xailabs.de"
REGISTRATION_NOTIFICATION_EMAIL = "cainbln@hotmail.com"
INTERCEPT_EMAIL= "ferhat.ipek@xailabs.de"

# Mail templates
REGISTRATION_SUBJECT = "Registration request"
REGISTRATION_TEMPLATE = "A new registration request: \n* email {{email}}\n* first_name: {{first_name}}\n* last_name: {{last_name}}\n* company: {{company}}\n* additional_info: {{additional_info}}"

INVITATION_SUBJECT = "You have been invited to a CPT questionary"
#INVITATION_MULTIGENCE_LOGO_URL = "https://s3.eu-central-1.amazonaws.com/statics.multigence.com/multigence_logo_full.png"

PASSWORD_RESET_SUBJECT = "Password reset request"
PASSWORD_RESET_TEMPLATE = "Hi,\n you have request a password reset. Click on {{link}} to proceed.\n\n\nHi\n du dein Passwort vergessen, click here {{link}}"

DEFAULT_DEPARTMENTS = ["Executive", "Legal", "HR", "Marketing", "Sales", "Finance", "Production", "Logistics", "Procurement", "IT"]

# RANDOM_FIRST_NAMES = ["Shonta","Ashlyn","Maryrose","Malisa","Maia","Mandie","Juliette","Creola","Leslie","Cherryl","Marquerite","Naoma","Tereasa","Lorine","Mitzie","Shawna","Charita","Madeline","Melynda","Tess","Shanika","Chu","Robbin","Chia","Mckinley","Yoko","Paz","Masako","Marlo","Doris","Marylyn","Jennell","Pamelia","Nelia","Silvia","Colene","Mackenzie","Shamika","Manda","Rudolph","Cherlyn","Lashawna","Rona","Cheryl","Cathey","Marquetta","Linh","Owen","Verena","Carmelina"]

RANDOM_FIRST_NAMES = ["admiring", "adoring", "agitated", "angry", "backstabbing", "berserk", "boring", "clever", "cocky", "compassionate", "condescending", "cranky", "desperate", "determined", "distracted", "dreamy", "drunk", "ecstatic", "elated", "elegant", "evil", "fervent", "focused", "furious", "gloomy", "goofy", "grave", "happy", "high", "hopeful", "hungry", "insane", "jolly", "jovial", "kickass", "lonely", "loving", "mad", "modest", "naughty", "nostalgic", "pensive", "prickly", "reverent", "romantic", "sad", "serene", "sharp", "sick", "silly", "sleepy", "stoic", "stupefied", "suspicious", "tender", "thirsty", "trusting"]

# RANDOM_LAST_NAMES = ["Russo","Mccann","Ellison","Mckinney","Griffin","Bonilla","Blackwell","Wilkinson","Melendez","Irwin","Black","Decker","Willis","Shannon","Hawkins","Pugh","Woods","Maddox","Jones","Sosa","Rush","Gilbert","Weiss","Carter","Benitez","Case","Foley","Rios","Cuevas","Strickland","Becker","Schwartz","Eaton","Kemp","Waters","Hubbard","Erickson","Roberts","Hobbs","Everett","Cooper","Hernandez","Mclaughlin","Huang","Rojas","Keller","Mcmahon","Chavez","Ho","Austin"]

RANDOM_LAST_NAMES = ["albattani", "almeida", "archimedes", "ardinghelli", "babbage", "banach", "bardeen", "brattain", "shockley", "bartik", "bell", "blackwell", "bohr", "brown", "carson", "colden", "cori", "curie", "darwin", "davinci", "einstein", "elion", "engelbart", "euclid", "fermat", "fermi", "feynman", "franklin", "galileo", "goldstine", "goodall", "hawking", "heisenberg", "hodgkin", "hoover", "hopper", "hypatia", "jang", "jones", "kirch", "kowalevski", "lalande", "leakey", "lovelace", "lumiere", "mayer", "mccarthy", "mcclintock", "mclean", "meitner", "mestorf", "morse", "newton", "nobel", "payne", "pare", "pasteur", "perlman", "pike", "poincare", "poitras", "ptolemy", "ritchie", "thompson", "rosalind", "sammet", "sinoussi", "stallman", "swartz", "tesla", "torvalds", "turing", "wilson", "wozniak", "wright", "yalow", "yonath"]
